import Providers from "@/components/providers";
import "@/styles/globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";

const roboto = localFont({
  src: "../public/fonts/Roboto-Variable.ttf",
  display: "swap",
  weight: "45 920",
  variable: "--font-roboto",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${roboto.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
