import { auth } from "@/auth";
import Providers from "@/components/providers";
import "@/styles/globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";

const roboto = localFont({
  src: "../public/fonts/Roboto-Variable.ttf",
  display: "swap",
  weight: "45 920",
  variable: "--font-roboto",
});
export const metadata: Metadata = {
  title: {
    default: "VantaHub",
    template: "%s - VantaHub",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="es">
      <body className={`${roboto.variable} antialiased`}>
        <Providers session={session}>{children}</Providers>
      </body>
    </html>
  );
}
